stages:
  train_cnn:
    cmd: python3 train.py
    deps:
      - src/train.py
      - src/data.py
      - src/model.py
      - src/evaluate.py
      - train.py
      - params.yaml
    params:
      - lr
      - batch_size
      - epochs
    outs:
      - outputs/model.pth
      - outputs/train_val_loss.csv
      - outputs/val_acc.csv
    metrics:
      - outputs/metrics.json

plots:
  - outputs/train_val_loss.csv:
      x: epoch
      y:
        - train_loss
        - val_loss
      title: "Training vs Validation Loss"
      x_label: "Epoch"
      y_label: "Loss"

  - outputs/val_acc.csv:
      x: epoch
      y:
        - val_acc
      title: "Validation Accuracy"
      x_label: "Epoch"
      y_label: "Accuracy (%)"