stages:
  train_cnn:
    cmd: python3 train.py
    deps:
      - src/train.py
      - src/data.py
      - src/model.py
      - src/evaluate.py
      - train.py
      - params.yaml
    params:
      - lr
      - batch_size
      - epochs
    outs:
      - outputs/model.pth
    metrics:
      - outputs/metrics.json

plots:
  - outputs/metrics.csv:
      x: epoch
      y: [train_loss, val_loss]
      title: "Training and Validation Loss"
      template: linear
      x_label: "Epoch"
      y_label: "Loss"

  - outputs/metrics.csv:
      x: epoch
      y: [val_acc]
      title: "Validation Accuracy"
      template: linear
      x_label: "Epoch"
      y_label: "Accuracy (%)"